import { Course } from "./types";

export const courses: Course[] = [
  {
    id: "MBA101",
    name: "Business Fundamentals",
    description: "Introduction to key business concepts and principles",
    credits: 3,
    category: "core",
  },
  {
    id: "MBA102",
    name: "Financial Accounting",
    description: "Understanding financial statements and accounting principles",
    credits: 3,
    category: "core",
    prerequisites: ["MBA101"],
  },
  {
    id: "FIN301",
    name: "Corporate Finance",
    description: "Advanced financial management and investment strategies",
    credits: 3,
    category: "finance",
    prerequisites: ["MBA102"],
  },
  {
    id: "MKT301",
    name: "Marketing Strategy",
    description: "Developing and implementing marketing strategies",
    credits: 3,
    category: "marketing",
    prerequisites: ["MBA101"],
  },
  {
    id: "MGT301",
    name: "Organizational Leadership",
    description: "Leadership principles and organizational behavior",
    credits: 3,
    category: "management",
    prerequisites: ["MBA101"],
  },
  {
    id: "FIN302",
    name: "Investment Analysis",
    description: "Portfolio management and investment decision-making",
    credits: 3,
    category: "finance",
    prerequisites: ["FIN301"],
  },
  {
    id: "MKT302",
    name: "Digital Marketing",
    description: "Online marketing strategies and analytics",
    credits: 3,
    category: "marketing",
    prerequisites: ["MKT301"],
  },
  {
    id: "MGT302",
    name: "Strategic Management",
    description: "Business strategy and competitive advantage",
    credits: 3,
    category: "management",
    prerequisites: ["MGT301"],
  },
  {
    id: "MBA401",
    name: "Business Analytics",
    description: "Data-driven decision making in business",
    credits: 3,
    category: "core",
    prerequisites: ["MBA102"],
  },
];